### ISSUE TITLE
Can't connect to server to get Asset folder

### ISSUE THREAD

**Issue by Knifesurge** [Mantaro/MantaroSelf#3]
Hi there!
The MantaroSelfbot won't run because it cannot connect to whatever server it gets the assets folder from. Running MantaroSelf-1.3.0_2.

![image](https://user-images.githubusercontent.com/11035429/27268842-58eff5c2-5480-11e7-9c48-24c7a5491615.png)

In the #selfbot-support channel in the Discord, Ion mentioned something about the address being an old address. (8081 in console when it should be 8111)

Thanks ¯\_(ツ)_/¯

**Comment by natanbc** [comment]
Update to the latest version

**Comment by adriantodt** [comment]
Update to the **latest** build by downloading the new version, which can be found [here](http://polr.me/getselfbot)!
